version: '3.8'

services:
  web:
    container_name: test
    image: test:0.0.1
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=QW123_0gFHksdfgZa
      - EXTERNAL_PORT=3000
      - PGDATABASE=test
      - PGUSER=test
      - PGPASSWORD=test
      - PGHOST=db
    depends_on:
      - db
  db:
    container_name: db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}

